#!/usr/bin/env node
/**
 * Bundle src/code.js + src/config/constants.js for Figma plugin main.
 * Figma sandbox does not support ES module import/export.
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const constantsPath = path.join(root, "src", "config", "constants.js");
const codePath = path.join(root, "src", "code.js");
const outPath = path.join(root, "dist", "code.js");

let constants = fs.readFileSync(constantsPath, "utf8");
constants = constants.replace(/^export const /gm, "const ");

let code = fs.readFileSync(codePath, "utf8");
code = code.replace(/^import\s*\{[\s\S]*?\}\s*from\s*["'][^"']+["'];\s*\n/m, "");

const banner =
  "// Auto-generated by scripts/build-code.js — do not edit.\n" +
  "// Edit src/code.js and src/config/constants.js, then run: npm run build\n\n";

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, banner + constants + "\n" + code);

const { execSync } = require("child_process");
try {
  execSync("node --check " + JSON.stringify(outPath), { stdio: "pipe" });
} catch (err) {
  console.error("Bundled dist/code.js has a syntax error:");
  console.error(String(err.stderr || err.message || err));
  process.exit(1);
}

const kb = Math.round(fs.statSync(outPath).size / 1024);
console.log("Bundled dist/code.js (" + kb + " KB)");
